name: Gitleaks - Scanning Secrets in PR

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
    types:
      - synchronize
      - opened
    branches:
      - 'main'
      - 'master'

jobs:
  scan:
    uses: DevSecOps-AppSec/reusable-workflows/.github/workflows/itLeaks_reusable_worflow.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use secrets directly in the calling workflow
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
