name: Gitleaks - Scanning Secrets in PR

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
    types:
      - synchronize
      - opened
    branches:
      - 'main'
      - 'master'

jobs:
  scan:
    uses: your-org-name/repository-name/.github/workflows/secret-scanning.yml@main
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}  # Passing secrets as inputs
      gitleaks_license: ${{ secrets.GITLEAKS_LICENSE }}
      
